alertmanager:
  config:
    route:
      receiver: 'null' # default receiver
      routes: 
      - match: 
          alertname: FlaskServiceDown # alert name
        receiver: 'webhook-receiver' # receiver name
        continue: true # continue to evaluate other routes
    receivers:
    - name: 'null'
    - name: 'webhook-receiver'
      webhook_configs:
      - url: "http://alert-service.jenkins.svc.cluster.local:5054/alert"
        send_resolved: true
