apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-contacts-app
  labels:
    app: flask-contacts-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-contacts-app
  template:
    metadata:
      labels:
        app: flask-contacts-app
    spec:
      containers:
      - name: flask-contacts-app
        image: shashkist/flask-contacts-app
        ports:
        - containerPort: 5052
        env:
        - name: DB_HOST
          value: database-1.ctsq2w8muuqh.us-east-1.rds.amazonaws.com
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: "12345678"       

       
---
apiVersion: v1
kind: Service
metadata:
  name: flask-contacts-app-service
  labels:
    app: flask-contacts-service # this should be mapped by service monitor
spec:
  selector:
    app: flask-contacts-app
  type: LoadBalancer  
  ports:
    - name: flask-contacts-service #this port name should be mapped by service monitor
      protocol: TCP
      port: 5055
      targetPort: 5052
       
